# Generated by Django 5.1.4 on 2024-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Por retirar'), ('B', 'Retirado'), ('C', 'En progreso'), ('D', 'Por entregar'), ('E', 'Entregado')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='imageitemorder',
            name='image',
            field=models.ImageField(upload_to='itemsOrders/'),
        ),
    ]
